version: '3'

services:
  nginx:
    image: nginx:1.11.10-alpine
    container_name: nginx
    networks:
      - flip_disbursment
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: ./
    env_file:
      - ./.env
    volumes:
      - .:/var/www/flip
    container_name: php_fpm
    networks:
      - flip_disbursment
    ports:
      - 9000:9000
  mysql:
    image: mysql:5.7
    env_file:
      - ./.env
    container_name: mysql
    volumes:
      - .:/var/www/flip
    networks:
      - flip_disbursment
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: flip
networks:
  flip_disbursment:
    driver: bridge
